apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: telegrammessages.harbur.harbur.io
spec:
  group: harbur.harbur.io
  names:
    kind: TelegramMessage
    plural: telegrammessages
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            chatid:
              type: string
            messagetodeliver:
              type: string
            token:
              type: string
          type: object
        status:
          properties:
            delivered:
              type: string
            messagedelivered:
              type: string
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
